### ISSUE TITLE
Network/firewallPolicies has wrong ShortName

### ISSUE THREAD

**Issue by ReneRebsdorf** [mspnp/AzureNamingTool#109]
**Tool version**
main branch

**Describe the bug**
Microsoft.Network/firewallPolicies short name should be 'afwp' instead of 'waf'

resourcetypes.json has:

```json
  {
    "id": 223,
    "resource": "Network/firewallPolicies",
    "optional": "UnitDept",
    "exclude": "Org,Function",
    "property": "",
    "ShortName": "waf",
    "scope": "resource group",
    "lengthMin": "1",
    "lengthMax": "80",
    "validText": "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric. End alphanumeric or underscore.",
    "invalidText": "",
    "invalidCharacters": "",
    "invalidCharactersStart": "",
    "invalidCharactersEnd": "",
    "invalidCharactersConsecutive": "",
    "regx": "^(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9_\\.-]{0,78}[a-zA-Z0-9_])$",
    "staticValues": ""
  },
```

However as per https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations
their abbreviation should be 'afwp'

This is relevant where the short name is used for name generation either as a postfix or prefix

**To Reproduce**
N/A

**Expected behavior**
afwp is the short name for azure firewall policies

**Screenshots**
N/A

**Installation Method**
N/A

**Additional context**
N/A

**Comment by Floriszz** [comment]
The resource Provider Namespace, Microsoft.Network/firewallPolicies, is mentioned twice at Link above. So both are correct I guess.
Confusing it is, but both fall under Firewall Manager anyway.

**Comment by ReneRebsdorf** [comment]
They are indeed but they are used for different resources, so they are correct under different contexts.

Since I assume there's no way to determine that context, the ShortName should probably be removed here, as it is misleading?
Maybe the regex should be updated to expect either 'waf' or 'afwp' in the name?

**Comment by BryanSoltis** [comment]
Hi @ReneRebsdorf ,

v4.3.0 was released with Custom Resource Type support. Please review the release notes and update to the latest version to customize your resource types.

https://github.com/mspnp/AzureNamingTool/wiki/v4.3.0

Bryan

**Comment by ReneRebsdorf** [comment]
Thank you for the heads up @BryanSoltis 
It is now on our backlog to utilize this feature. :)
