### ISSUE TITLE
Exclude/Include/Custom delimiter for specific resource types

### ISSUE THREAD

**Issue by Jared975** [mspnp/AzureNamingTool#11]
**Is your feature request related to a problem? Please describe.**
Managed disks for example, can include a delimiter, but the tool does create disk names with delimiters.
Its great that for most resources it auto-removes the delimiter, but there are environments where clients dont want to use delimiters for specific resource types, and want them in others.

![image](https://github.com/mspnp/AzureNamingTool/assets/34285804/26757f43-8f7f-4c85-a092-331cf7934354)

**Describe the solution you'd like**
A button on the Edit Resource Type window in the same section as minimum/maximum length requirement.

**Describe alternatives you've considered**

allowing delimiters for disk names would probably be the easiest solution, but then people who dont want delimiters in their disk names are forced to have them or manually remove them...

manually adding the delimiter to the disk name after generating it - not ideal

**Additional context**
![image](https://github.com/mspnp/AzureNamingTool/assets/34285804/73c3aa54-f8a2-40d9-9071-5a11faa5b66c)

**Comment by BryanSoltis** [comment]
Hello @Jared975,

Thank you for your suggestions. We have added it to our backlog and will evaluate this feature for a future release.

- Bryan
