### ISSUE TITLE
Custom resource types

### ISSUE THREAD

**Issue by jnantg** [mspnp/AzureNamingTool#110]
**Tool version**
4.2.1

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to be able to add custom resource types. For example general entra groups, intune configurations and the likes. This would me it possible to generate names for other Entra resources that have a defined naming standard in an organization

**Comment by BryanSoltis** [comment]
Hi @jnantg,

Thank you for the Feature Request. This functionality is actually already developed and will be released in the next version (most likely mid-end Sept). Please keep an eye on the repo for release of v4.3.0!

- Bryan

**Comment by jnantg** [comment]
Hi!


Any news on version 4.3? I have been looking forward to it, but cannot find any news on the subject



________________________________

**Comment by kc8421** [comment]
Custom resource types would be very welcome. There are many resources missing.

**Comment by BryanSoltis** [comment]
Hi @jnantg,

v4.3.0 was released with Custom Resource Type support. Please review the release notes and update to the latest version to customize your resource types.

https://github.com/mspnp/AzureNamingTool/wiki/v4.3.0

Bryan
