### ISSUE TITLE
Deployement with Githugb Actions failed

### ISSUE THREAD

**Issue by dhaferh** [mspnp/AzureNamingTool#115]
**Tool version**
Current version of the Azure Naming Tool you are running.

**Describe the bug**

[deploy](https://github.com/microsoft/AzureNamingTool/actions/runs/11374073142/job/31642166913#step:2:12)
Unable to download artifact(s): Artifact not found for name: .net-app
        Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact

**Screenshots**

<img width="702" alt="image" src="https://github.com/user-attachments/assets/d24cec5c-d877-4ca1-9bda-f65ea7e4495c">

**Comment by BryanSoltis** [comment]
Thank you for reporting. I've updated the GitHub Action to v4+ of the upload and download artifact steps. This should be resolved. 

- Bryan

**Comment by BryanSoltis** [comment]
Closing as resolved.
