### ISSUE TITLE
Issue Generating Name for Windows VM

### ISSUE THREAD

**Issue by rich872** [mspnp/AzureNamingTool#20]
**Describe the bug**
When trying to generate a name for a Windows VM it always generates a name for a Linux VM so the delimiter is present when it shouldn't be in the name.  See attached pic.

**To Reproduce**
1. Go to Generated
2. Select Compute for category
3. Select Compute/virtualMachines - Windows (vm)
4. Fill out all fields
5. Click Generate

**Expected behavior**
When you generate a name for a Windows VM it should generate a name for a Windows (not Linux) VM.

**Screenshots**

**Installation Method**
Docker Container

**Additional context**
Version 3.02

<img width="562" alt="image" src="https://github.com/mspnp/AzureNamingTool/assets/1874637/6b02ca79-9217-49cc-993a-a57058702e57">

**Comment by BryanSoltis** [comment]
Hi @rich872,

Thank you for your feedback!  This issue is due to an issue with the auto-complete filed on the Generate page.  This will be resolved in our next release. 

- Bryan

**Comment by rich872** [comment]
Thanks Bryan.  Any idea when next release is due to come out?

**Comment by BryanSoltis** [comment]
V3.1.0 will most likely release next week some time. I have implemented the changes (along with other enhancements) but am still testing.  If you like, you can view the new functionality in the Pre-Lease version here:

[v3.1.0 Pre-Release](https://github.com/mspnp/AzureNamingTool/releases/tag/v3.1.0)

- Bryan

**Comment by rich872** [comment]
Fantastic, I'll check it out.  BTW - great work on this tool.  We are just starting to build out our Azure space to begin moving workloads and have been struggling with naming conventions.  We found this tool and it has made things so much simpler for us.  Excellent work!  :)

**Comment by BryanSoltis** [comment]
Thank you for the feedback! We love hearing that the tool is helping, but also we want to implement improvements where we can.

If you had a moment, we always appreciate feedback here:  

[Feedback Form](https://forms.office.com/r/M2EZLg6zKq)

**Comment by BryanSoltis** [comment]
This has been resolved in V3.1.0, which is now released!

-Bryan
