### ISSUE TITLE
Name availability checking against Azure tenant

### ISSUE THREAD

**Issue by captainhook** [mspnp/AzureNamingTool#25]
**Is your feature request related to a problem? Please describe.**
It's possible that users generate a name but do not use it and therefore the next time a resource name is generated it will increment to the next available name.

**Describe the solution you'd like**
AzureNamingTool should scan the Azure tenant to see whether the name is taken and avoid incrementing.

**Describe alternatives you've considered**
We could do a regular scan against our Azure tenant and then delete unused names using the AzureNamingTool.

**Additional context**
I can imagine this introducing a problem/conflict in a heavy traffic environment where the tool is being used regularly.

**Comment by BryanSoltis** [comment]
Hello @captainhook,

Thank you for your suggestion. The Azure Naming Tool currently does not have any connectivity/communication back to the Azure tenant. This is to simplify the security and to ensure the tool is 100% self-contained and able to be run when there is no internet connectivity. We have Azure-integration as part of our backlog and will evaluate adding this in a future release. 

Thank you!

- Bryan
