### ISSUE TITLE
Config Import Screen working indefinitely

### ISSUE THREAD

**Issue by ArlanNugara** [mspnp/AzureNamingTool#28]
**Describe the bug**
When we import a config a pop up shows **(Global) Global Config Update Succeeded** whereas the screen shows **Working** indefinitely and does not go back to Configuration page or Home page.

**To Reproduce**
1. Go to **Configuration**
2. Click on **Global Configuration** under **General Configuration**
3. Scroll down to **Import Global Configuaration**
4. Paste the backed up json of global config
5. Click on **Import** button
6. Click on **OK** button on Attention pop up
7. Click on **OK** button on Attention pop up again

**Expected behavior**
A pop up showing Success / Failure in loading the global config and go back to Configuration page or home page.

**Screenshots**
![image](https://github.com/mspnp/AzureNamingTool/assets/25376123/c70143ef-7144-4234-8c2c-4913698fc454)

**Installation Method**
As per official document [here](https://github.com/mspnp/AzureNamingTool/wiki/Run-as-a-Web-App-for-Containers).

**Comment by BryanSoltis** [comment]
Hi @ArlanNugara,

Thank you for feedback! We will research this issue and include a fix in the next release.

- Bryan

**Comment by BryanSoltis** [comment]
Hi @ArlanNugara,

I have continued to research this and remembered we had a fix for this in the last update. Can you confirm what version of the tool you are running? If you go to the Admin page, it will show the current version at the top.

Thank you!

-Bryan

**Comment by BryanSoltis** [comment]
Closed due to inactivity

**Comment by ArlanNugara** [comment]
@BryanSoltis  Sorry for late response. The version we are using is 3.1.0 and the issue is still persisting. Do you think upgrading to 3.1.1 will fix the issue ?

**Comment by ArlanNugara** [comment]
@BryanSoltis The issue persists in 3.1.0.

![image](https://github.com/mspnp/AzureNamingTool/assets/25376123/adc4f68e-b79b-4fd9-a5e6-f57f04d786b5)

**Comment by BryanSoltis** [comment]
When v3.1.0 was released I had updated the Global Configuration to handle this, so I'm a little curious as to what is causing it. I may have to see your configuration and step through the code to test it. I will cr4eate a private repo and invite you shortly for collaborati0on.

-Bryan

**Comment by BryanSoltis** [comment]
Closed due to inavtivity.

**Comment by ArlanNugara** [comment]
@BryanSoltis  Sorry, we can not share our configurations with you. However, the issue persists with / without specific configuration. And we are getting used to the issue..
