### ISSUE TITLE
Missing location: Sweden Central

### ISSUE THREAD

**Issue by stefan-berglund** [mspnp/AzureNamingTool#29]
**Is your feature request related to a problem? Please describe.**
The Azure location Sweden Central is missing in the Azure Naming Tool. We're using version 3.1.0 and the configuration have been updated today but this location is still missing.

**Describe the solution you'd like**
Being able to choose Sweden Central when generating a resource name.

**Comment by BryanSoltis** [comment]
Hi @stefan-berglund ,

Thank you for your feedback. Will add this to our next release.

- Bryan
