### ISSUE TITLE
Enable the ability to do a bulk import of records into a custom component.

### ISSUE THREAD

**Issue by blaqvikin** [mspnp/AzureNamingTool#34]
**Tool version**
V3.0.0

**Is your feature request related to a problem? Please describe.**
I am trying to do a bulk import of values for a custom component.

**Describe the solution you'd like**
Can we have the ability to programmatically do a bulk import of values into a custom component?

**Describe alternatives you've considered**

**Additional context**

**Comment by BryanSoltis** [comment]
Hello @blaqvikin,

Thank you for your feedback. We have added this functionality to our backlog and will evaluate adding it in a future release.

- Bryan

**Comment by BryanSoltis** [comment]
Added to backlog. Closing issue.
