### ISSUE TITLE
Ability to do a bulk import of records into a custom component via Pwsh API call

### ISSUE THREAD

**Issue by blaqvikin** [mspnp/AzureNamingTool#35]
**Tool version**
2.7.0

**Describe the bug**
I am checking if it is possible for me to import bulk records into a custom component via a Pwsh API call?

**To Reproduce**

This is a post body to create an NSG, would it be possible to have something similar but intended for adding multiple records under the BusinessUnit key?
    "NetworkSecurityGroup1" = @{
        ResourceType = "nsg"
        customComponents = @{
            ResourceEnvironments = "prod"
            **BusinessUnit = "marketing"**
            ResourceRegions = "san"
            ResourceTypeSubset = "subn"
            ResourceIdentifier = "db"
        }
    }

**Expected behavior**
I am expecting to have multiple records under the businessunit key.

**Screenshots**

**Installation Method**
The installation is running on a container in Azure.

**Additional context**

**Comment by BryanSoltis** [comment]
Added to backlog. Closing the issue.
