### ISSUE TITLE
Missing resource names/short names for Container Apps and Container Apps Environment.

### ISSUE THREAD

**Issue by omon77** [mspnp/AzureNamingTool#37]
**Tool version**
v3.1.1

**Describe the bug**
Missing some of the resource types and their abbreivations, specifically Container Apps and Container Apps Environments.
<html>
<body>

Resource | Resource provider namespace | Abbreviation
-- | -- | --
Container apps | Microsoft.App/containerApps | ca
Container apps environment | Microsoft.App/managedEnvironments | cae

<br/>

</body>
</html>

**To Reproduce**
N/A

**Expected behavior**

**Screenshots**
N/A

**Installation Method**
N/A

**Additional context**
Please see this for reference: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations

**Comment by jamasten** [comment]
@omon77 we have added this to our backlog and will add these in a future update.  Thanks!

**Comment by cyrilzhouibo** [comment]
Has this been fixed? I can't find Container apps in V 4.2.0
