### ISSUE TITLE
500 Error from AppService

### ISSUE THREAD

**Issue by tirrellcotton** [mspnp/AzureNamingTool#38]
I followed the instructions to deploy as an Azure Web App using Github Actions.  Everything deployed as expected, but when I open the web app url I get a 500 error.  The only way I can get in is to turn off authentication.   Am I missing something?  I'm pretty new to Azure so any assistance would be appreciated.

**Comment by BryanSoltis** [comment]
Hi @tirrellcotton,

Thank you for your feedback. Can you elaborate on the actual 500 error? Enabling the authentication is a highly recommended action so only authorized users can access it. Also, can you let me know the version of the tool you are running?

Thank you.
-Bryan

**Comment by BryanSoltis** [comment]
If you could provide any logs/error details, I can try and research what would be causing the issue. Here are some guides to help you research/find error logs.

https://learn.microsoft.com/en-us/azure/app-service/overview-diagnostics

https://learn.microsoft.com/en-us/azure/app-service/troubleshoot-http-502-http-503

https://learn.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#enable-application-logging-linuxcontainer

-Bryan

**Comment by tirrellcotton** [comment]
Don't know why I cannot seem to get any logs, but do have a question.  When adding the app service via GitHub actions, step 3: Enable Azure Web App Authentication I selected "Microsoft", but what name should I have entered?  It seems my issue is with authentication and I feel this is where things may have gone wrong.  I entered the same name as my app service, was this correct?

**Comment by BryanSoltis** [comment]
From a code perspective, there is very little interaction with Authentication, Primarily, the tool just looks for specific headers and if they are present, it enables some functionality. A 500 Error indicates the request got to the server, however, it threw an exception.

If you could provide any screen shots, if would help:
- The 500 error
- The Developer Tools console when the error occurs (f12 in your browser)
- Then Authentication configuration of your app service (Be sure to blur any sensitive values)

-Bryan

**Comment by tirrellcotton** [comment]
Here you go, thanks.
![app auth settings](https://github.com/mspnp/AzureNamingTool/assets/1261133/a9831326-e9b7-492e-8424-7bfb13dfd156)
![azure 500 error](https://github.com/mspnp/AzureNamingTool/assets/1261133/2eea621f-9c3f-48f7-9bc0-03858aea89c7)

**Comment by BryanSoltis** [comment]
OK, thank you for the info. I think seeing the actual 500 error being thrown is critical, as it will specify what the issue is. I would recommend using the links above to investigate the App Service diagnostics. This will be different if you are using a Windows vs Linux App Service. 

You may want to create a new app service and try to the process again. Perhaps something got messed up in the intial deployment. 

-Bryan

**Comment by tirrellcotton** [comment]
Redeployed as a Windows app service instead of Linux and that seems to work.  Thanks for your time 😊

**Comment by BryanSoltis** [comment]
Thank you for the update. I have my dev site deployed to a Linux app, so perhaps something just got out of sync on your initial deployment. Glad to hear it's working for you now!

- Bryan
