### ISSUE TITLE
Location missing - Central Poland

### ISSUE THREAD

**Issue by PawelIntegrity** [mspnp/AzureNamingTool#47]
**Tool version**
Current version: 3.1.1 

**Is your feature request related to a problem? Please describe.**
Its missing location Central Poland

**Describe the solution you'd like**
Adding location Central POland

**Describe alternatives you've considered**
Non alternative

**Additional context**
N/A

**Comment by PawelIntegrity** [comment]
Nevermind, there as "Refresh the Resource Locations Configuration"

**Comment by BryanSoltis** [comment]
Hi @PawelIntegrity,

Glad you found the Refresh option! Also, in v3.2.0 that was released last week, you can add custom locations, if needed.

-Bryan

**Comment by PawelIntegrity** [comment]
Yeah, I just upgraded it as well thanks a lot

**Comment by PawelIntegrity** [comment]
Is there any quick way to export all the Short names of Resource Types? I need it to write syntax in Azure Policy. Let me know if I need to open another "ticket". I found the files in wwwroot/settings/resourcetypes.json however that won't be very covenient to get them one by one or I just don't know any bulk way
