### ISSUE TITLE
Short Name must be...

### ISSUE THREAD

**Issue by PawelIntegrity** [mspnp/AzureNamingTool#49]
**Tool version**
Current version: 3.2.0

**Describe the bug**
In configuration section > Current Projects/Apps/Services when I edit the Project/App/Service.
It says that: short Name must be 1-3 characters.

**To Reproduce**
N/a

**Expected behavior**
I need it to be max 4 or even 5, how can I change it?

**Screenshots**
![image](https://github.com/mspnp/AzureNamingTool/assets/151019521/018aa6c8-bf11-4225-b425-13be01748a3f)

**Installation Method**
n/a

**Additional context**
I need it to be max 4 or even 5, how can I change it?

**Comment by BryanSoltis** [comment]
Hi @PawelIntegrity,

This functionality is currently not available in the tool. We may add this at a later time. As an alternative, you could add a Custom Component, which allows Short Name values up to 10 characters. 

- Bryan

**Comment by PawelIntegrity** [comment]
Hello,

Can you show me how to do it?

Br
Paweł



[cid:d37bbcf3-aff0-4e41-91b2-acc06596e8fd.png]  Paweł Rybczyński
Microsoft Hybrid Cloud Solution Specialist

Mobile +48 882 398 041
Teams +48 882 398 041


Integrity Partners Sp. z o.o.
ul. Chłodna 51, 00-867 Warszawa
Office
[cid:SocialLink_Linkedin_32x32_332a0918-6c3d-4064-9a1a-ee6a4bf17cdc.png]<https://pl.linkedin.com/company/integrity-partners-cloud-security>

Sąd Rejonowy dla m. st. Warszawy w Warszawie, XII Wydział Gospodarczy Krajowego Rejestru Sądowego,
KRS: 0000347184, NIP 527-262-00-67. Adres rejestrowy Firmy - ul. Chłodna 51, 00-867 Warszawa.

<https://integritypartners.pl/microsoft-partner-awards-2022/>[cid:stopkamailowa900x215potymicrosoft2023_f2546f1a-710b-4a68-91dc-91745100f68e.png]<https://integritypartners.pl/integrity-partners-triumfuje-jako-partner-roku-microsoft-2023/>

**Comment by BryanSoltis** [comment]
You can add custom components by:

1. On the Configuration Page / Components, select ** Add Component** 

![image](https://github.com/mspnp/AzureNamingTool/assets/13591910/478e500d-88c8-41e4-b558-61664aa6774d)

2. Enter the desired name, min length, max length, and select **Standard** for the Field Type.

![image](https://github.com/mspnp/AzureNamingTool/assets/13591910/0c86ac41-99a3-42b4-a181-e70533d99067)

3. Expand the ***Custom Components** tab and select **Add Component**

![image](https://github.com/mspnp/AzureNamingTool/assets/13591910/21c89a4d-539c-4de3-a2f9-c309f78513b8)

4. Enter the desired component option values. Note the min/max lengths from your component configuration. 

![image](https://github.com/mspnp/AzureNamingTool/assets/13591910/599fdb94-f040-4f89-88cf-b3ee431fc0a3)


Once enabled (on the Configuration / Components tab), your custom component/options will be available on the **Generate** page.

![image](https://github.com/mspnp/AzureNamingTool/assets/13591910/8e03ea83-2d00-4e11-9848-beb2cfef607b)

**Comment by PawelIntegrity** [comment]
Thanks for that, I'll test it


[cid:d37bbcf3-aff0-4e41-91b2-acc06596e8fd.png]  Paweł Rybczyński
Microsoft Hybrid Cloud Solution Specialist

Mobile +48 882 398 041
Teams +48 882 398 041


Integrity Partners Sp. z o.o.
ul. Chłodna 51, 00-867 Warszawa
Office
[cid:SocialLink_Linkedin_32x32_332a0918-6c3d-4064-9a1a-ee6a4bf17cdc.png]<https://pl.linkedin.com/company/integrity-partners-cloud-security>

Sąd Rejonowy dla m. st. Warszawy w Warszawie, XII Wydział Gospodarczy Krajowego Rejestru Sądowego,
KRS: 0000347184, NIP 527-262-00-67. Adres rejestrowy Firmy - ul. Chłodna 51, 00-867 Warszawa.

<https://integritypartners.pl/microsoft-partner-awards-2022/>[cid:stopkamailowa900x215potymicrosoft2023_f2546f1a-710b-4a68-91dc-91745100f68e.png]<https://integritypartners.pl/integrity-partners-triumfuje-jako-partner-roku-microsoft-2023/>

________________________________

**Comment by PawelIntegrity** [comment]
hello

Is there any way to reset the global admin password in case if its eg. Forgotten?



Paweł Rybczyński
Microsoft Hybrid Cloud Solution Specialist
Mobile +48 882 398 041
e-mail ***@***.***

**Comment by PawelIntegrity** [comment]
Hello,

Your solution regards editing components worked, that's what I needed. Thanks!

Please let me know just in case "Is there any way to reset the global admin password in case if its eg. Forgotten? "

Moreover, I saw that when I generate naming convention string for virtual machines (windows) it removes my default delimiter which is "-", why? Can I fix it? It is allowed in azure so it should be allowed here.




Paweł Rybczyński
Microsoft Hybrid Cloud Solution Specialist
Mobile +48 882 398 041
e-mail ***@***.***
From: Paweł Rybczyński ***@***.***>
Sent: Friday, November 24, 2023 9:28 AM
To: mspnp/AzureNamingTool ***@***.***>; mspnp/AzureNamingTool ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [mspnp/AzureNamingTool] Short Name must be... (Issue #49)

hello

Is there any way to reset the global admin password in case if its eg. Forgotten?




Paweł Rybczyński
Microsoft Hybrid Cloud Solution Specialist
Mobile +48 882 398 041
e-mail ***@***.******@***.***>

**Comment by BryanSoltis** [comment]
All of the configuration data is stored in the **/settings** folder where you have the tool installed. If you open the **/settings/appsettings.json** file and clear out the value for **AdminPassword**, the site will prompt you to enter a new password.  Thaqt woudl be the only way to "reset" the password.

**Comment by PawelIntegrity** [comment]
Thanks for that



[cid:d37bbcf3-aff0-4e41-91b2-acc06596e8fd.png]  Paweł Rybczyński
Microsoft Hybrid Cloud Solution Specialist

Mobile +48 882 398 041
Teams +48 882 398 041


Integrity Partners Sp. z o.o.
ul. Chłodna 51, 00-867 Warszawa
Office
[cid:SocialLink_Linkedin_32x32_332a0918-6c3d-4064-9a1a-ee6a4bf17cdc.png]<https://pl.linkedin.com/company/integrity-partners-cloud-security>

Sąd Rejonowy dla m. st. Warszawy w Warszawie, XII Wydział Gospodarczy Krajowego Rejestru Sądowego,
KRS: 0000347184, NIP 527-262-00-67. Adres rejestrowy Firmy - ul. Chłodna 51, 00-867 Warszawa.

<https://integritypartners.pl/microsoft-partner-awards-2022/>[cid:stopkamailowa900x215potymicrosoft2023_f2546f1a-710b-4a68-91dc-91745100f68e.png]<https://integritypartners.pl/integrity-partners-triumfuje-jako-partner-roku-microsoft-2023/>
