### ISSUE TITLE
Azure App Service Logout

### ISSUE THREAD

**Issue by koalajama** [mspnp/AzureNamingTool#53]
**Tool version**
3.2.0

**Describe the bug**
When logged in with Azure AD Authentication and users click the 'logout' button in the top right corner, the screen reloads and the "User: username@domain.com" banner goes away. I have my front-channel logout URL set to _url_/.auth/logout/complete, and after the user logs out, they are still able to use the tool. 

**To Reproduce**
1. Setup Azure App Service Auth

**Expected behavior**
Logging out would navigate to the Microsoft login screen. Requiring login before next use of the tool. 

**Screenshots**
![NamingTool02](https://github.com/mspnp/AzureNamingTool/assets/150177018/1b850565-90fa-413a-984d-6cfeab03d303)
![NamingTool01](https://github.com/mspnp/AzureNamingTool/assets/150177018/d6dc8849-95b1-41d0-a45f-f048219d4f09)
![NamingTool03](https://github.com/mspnp/AzureNamingTool/assets/150177018/a7d6c105-c645-4b01-b0de-1c3b042e1d82)

**Installation Method**
Azure App Service

**Additional context**

**Comment by BryanSoltis** [comment]
Hello @koalajama,

Thank you for your feedback. The Identity Provider support within the tool only looks at the incoming request and displays/associates activity with the identified user, if the specified headers are present (defined in the Admin utility). The tool does not "log" them in/out.  If using Authentication with an Azure App Service, Azure Entra will inject a header into the incoming request. The Naming Tool will look for this header and, if present, display the user information. Additionally, if the user id is identified as an "admin", certain functionality will be available. When a user "logs out", they are telling the tool to not apply the Identity Provider information and function as a "normal" user.

You can find more details about the Identity Provider support in the following article:

https://soltisweb.com/blog/detail/2023-06-azurenamingtool-identityproviderintegrationdeepdive

Hope this helps!

-Bryan
