### ISSUE TITLE
Deployment failed to Azure Web App

### ISSUE THREAD

**Issue by Afd-tech** [mspnp/AzureNamingTool#60]
![Screenshot 2023-12-20 093940](https://github.com/mspnp/AzureNamingTool/assets/54807820/2d151632-3190-4260-bbc0-ac74ba4d1a76)

**Comment by BryanSoltis** [comment]
Hello @Afd-tech,

Thank you for your feedback. In looking at the error, it seems as if your publish profile is incorrect, or you do not have the correct credentials. The documentation guides through setting these GitHub secrets up.

https://github.com/mspnp/AzureNamingTool/wiki/Run-as-an-Azure-Web-App-Using-GitHub-Action

I hoe this helps!

- Bryan

**Comment by BryanSoltis** [comment]
Closed due to inactivity.
