### ISSUE TITLE
Unable to edit or remove generated names (one or a few at a time).

### ISSUE THREAD

**Issue by alexbenitez** [mspnp/AzureNamingTool#61]
**Tool version**
Dec 5, 2023  (Commit e688d15774ba140f0a231b895ed08ce17b93bc4f)

**Is your feature request related to a problem? Please describe.**
I generated a few names to get familiar with the tool. The log is read-only and the "Purge" button is restricted.  I would like to clean up the list... but I can't

**Describe the solution you'd like**
There should be a way to list, edit, or remove generated names..

**Describe alternatives you've considered**

**Additional context**

**Comment by BryanSoltis** [comment]
Hi @alexbenitez,

The Allow Duplicate Names setting enables/disables the Purging of the Event Log. Enabling this setting will allow you purge the log / delete Indvidual entries.

![image](https://github.com/mspnp/AzureNamingTool/assets/13591910/350c0544-aabb-4b3f-b994-920151104e03)

We will update the setting details to state this in the next release.

- Bryan
