### ISSUE TITLE
Resource instance autoincrement feature does not adhere to minimum length requirement of field

### ISSUE THREAD

**Issue by ib134866** [mspnp/AzureNamingTool#64]
**Tool version**
3.3.0

**Describe the bug**
The instance component is configured for a minimum length of 2 and a maximum length of 5.  Apply delimiter before and apply delimiter after are both set.  The allow duplicate names is disabled.
Using the /api/ResourceNamingRequests/RequestName get, with the resourceInstance defined as "00", the first two calls to the API provide a resource name with a instance of 00 and 01 as expected, however the third call returns 2 without the leading zero and would fail the requirement to have a minimum length of 2 characters.

**To Reproduce**
1. Edit the instance component in Configuration/Base Configuration/Components
2. Change the minimum length from 1 to 2 and apply the change
3. Click Admin
4. Under site settings, enable "Allow  Duplicate Names"
5. Click Generated Names Log
6. Click Purge Generated Names Log to remove all currently issued names
7. Click Admin
8. Under site settings, disable "Allow Duplicate Names"
9. Generate a API call with the resourceInstance equal to "00"
10. Resource is created with a instance of "00"
11. Re-run the API call without changing the resourceInstance
12. Resource is created with a instance of "01" and a message is returned by the API - "The resource instance has been auto-incremented to the next value."
13. Re-run the API call without changing the resourceInstance
14. Resource is created with a instance of "2" and a message is returned by the API - "The resource instance has been auto-incremented to the next value."

**Expected behavior**
The expected behavior is that the resourceInstance on the third call would maintain the leading zero, like the second API call and would also adhere to the minimum length of 2 set for the instance component.

**Screenshots**
![image](https://github.com/mspnp/AzureNamingTool/assets/44326821/ade0e807-6111-4819-a9d5-803f4a12c955)

**Installation Method**
Azure Naming tool is running on a PodMan docker image on Windows 11 with WSL2 enabled.

**Comment by BryanSoltis** [comment]
Hello @ib134866,

Thank you for your feedback! I have confirmed this is an issue. It actually applied to the API, as well as the Generate page. This will be fixes in the next version (v4.0.0). Thank you!

-Bryan

**Comment by ib134866** [comment]
I can confirm the issue is fixed in V4.0.0.  Thank you

**Comment by BryanSoltis** [comment]
Awesome! We are still testing v4.0.0 (currently in pre-release) so please let me know if you encounter any issues with update/update to .NET. Thank you!

- Bryan
