### ISSUE TITLE
Data Collection - related resource types

### ISSUE THREAD

**Issue by alenat10** [mspnp/AzureNamingTool#76]
**Tool version**
4.0

**Is your feature request related to a problem? Please describe.**
It would be nice to have an option to keep all names in one place

**Describe the solution you'd like**
If possible, please add Data Collection Rule (dcr), Data Connection Endpoint (dce) and data collection rule association (dcra) in types  .json. I guess the types should be under Insights collection. 

**Describe alternatives you've considered**
manually create names for the abovementioned resources.

**Additional context**

**Comment by BryanSoltis** [comment]
Hello @alenat10,

Thank you for your feedback. We will add these resource types to the configuration and try to include them in the next release.

Thank you!

-Bryan
