### ISSUE TITLE
Leverage "Optional" functionality while generating multiple resource type names  

### ISSUE THREAD

**Issue by lucafabbri365** [mspnp/AzureNamingTool#77]
**Tool version**
v4.0.0

**Is your feature request related to a problem? Please describe.**
Optional or excluded components are required during the filling of fields (**Generate** section), when the _Generate Multiple Resource Type Names_ option is selected. The names of excluded components do not appear in the generated names, ALWAYS.
It may happen instead that the name of a component sometimes needs to be included, while at other times it should be omitted in generated names.
So, it would be useful to extend the usage of 'optional' component when the _Generate Multiple Resource Type Names_ option is selected.

Regards,
Luca

**Comment by BryanSoltis** [comment]
Hi Luca,

This is already part of our backlog, the current tool design makes implementation difficult. We will continue to evaluate this capability for future releases.

- Bryan
