### ISSUE TITLE
Allow configuration of uppercase resource names for selected resource types

### ISSUE THREAD

**Issue by danstis** [mspnp/AzureNamingTool#79]
**Tool version**
4.0.0

**Is your feature request related to a problem? Please describe.**
Our naming convention uses uppercase resource names where possible, so we would like the naming tool to allow generation of uppercase names depending on the resource type.

**Describe the solution you'd like**
I would like to have a toggle switch on each resource type that allows the selection of upper/lower case names. This should be a per resource option and to ensure it is not incorrectly used we could check the resource type regex to ensure it supports uppercase names before showing this new toggle.
If this new toggle is set to uppercase, the generated name would be converted to uppercase at generation time.
The examples in the reference section should also be converted to uppercase if this switch is toggled for the resource type.

**Comment by BryanSoltis** [comment]
Hi @danstis,

Thank you for your feedback. I've researched this enhancement, however, I'm coming up against a logical/process-related issue. In your message you are suggesting a setting//configuration on the resource type level. While this would be fairly easy to implement, the site doesn't store components on an individual resource type level. To further explain, all the components/options are stored on a "global" level, meaning the same component values are used for any name generation. 

Currently, the site will convert any component values to lowercase, to enforce compliance with many Azure Services. So, while a configuration be put on a resource type, all of the components selected would still be limited on their entry/management to be lowercase. The only solution here is to allow uppercase across the entire tool, which we will need to evaluate as whether that is a logical/good change to make. 

If we did go the "resource type configuration" route, we could add an option for each resource type that would convert ANY generated name to ALL UPPERCASE. That too, would be a fairly simple change, but I would want to validate it meets the need.

WE will discuss this on our next backlog planning call and see what makes sense. Feel free to add any more details/comments, in the event I misunderstood the request in any way.

Thank you!

-Bryan

**Comment by BryanSoltis** [comment]
Hi @danstis,

I wanted to provide a follow-up on this. As a result of our backlog planning, we decided to update the tool to allow Uppercase & Lowercase characters for all components. This will feature will be included in the next release (v4.1.0). 

- Bryan
