### ISSUE TITLE
Pre-built Docker images

### ISSUE THREAD

**Issue by DevSecNinja** [mspnp/AzureNamingTool#83]
**Tool version**
N/A

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I wanted to deploy the solution and noticed that I need to build the Docker image myself. It would be awesome if this project could publish a Docker image to either Docker Hub or as a GitHub package so that users can easily deploy the container and keep up-to-date with the project. That would make it super easy for all the container scenarios to deploy the application.

**Describe alternatives you've considered**
N/A

**Additional context**
There is a complete description here that builds the image and pushes it as a GitHub artifact:  https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

Thank you!

**Comment by BryanSoltis** [comment]
This will be added to Backlog and considered for a future release. 

- Bryan

**Comment by BryanSoltis** [comment]
Just to provide an update, we determined that the GitHub org we are currently hosted in does not allow "Public" packages. Without that capability, we are unable to host a pre-built image for the tool. If that ever changes, we will definitely add this functionality in a future release.

- Bryan

**Comment by DevSecNinja** [comment]
Thanks for looking into that Bryan! Is it possible to get them hosted at the Microsoft docker repo like this one? https://hub.docker.com/_/microsoft-dotnet-sdk/

**Comment by BryanSoltis** [comment]
We have looked into that, however, it would quire us hosting the tool in a different Org, along with other changes.  The Patterns & Practices org (our current home) gives us a lot of flexibility and autonomy, so we will be here for the foreseeable future. 

- Bryan

**Comment by andrew-flatters-bliss** [comment]
Does look like Microsoft has started publishing things to https://mcr.microsoft.com/en-us/catalog?alphaSort=asc&alphaSortKey=Name with the recent Docker Hub licence changes - might be a good place for a prebuilt image to end up?
