### ISSUE TITLE
Azure Data Factory Naming and dashes

### ISSUE THREAD

**Issue by pkrzysz** [mspnp/AzureNamingTool#91]
**Tool version**
4.0 / 4.0.1

**Describe the bug**
Azure Data factory naming for factory or linked service does not correspond to [standard](https://learn.microsoft.com/en-us/azure/data-factory/naming-rules). 

**To Reproduce**
1. Create any linked service or data factory with standard rules, using dash as delimiter

**Expected behavior**

- data factory - dashes are omitted
- linked services - dashes are omitted

**Comment by BryanSoltis** [comment]
Hi @pkrzysz ,

v4.3.0 was released with Custom Resource Type support. Please review the release notes and update to the latest version to customize your resource types.

https://github.com/mspnp/AzureNamingTool/wiki/v4.3.0

Bryan
