### ISSUE TITLE
Deployed 4.1.0 and just getting default Azure App Service page.

### ISSUE THREAD

**Issue by epfaffinger** [mspnp/AzureNamingTool#94]
I just deployed version 4.1.0 to a new app service and the workflow task completed successfully but all that is displayed is the default Azure app service page indicating "your app is running and waiting for content?

I deployed 4.0.1 using the same install process with no issue? Let me know if you need any logs. I've deleted the app services and followed the install for "Run as an Azure Web App Using GitHub Action" again resulting in the same issue.

**Comment by epfaffinger** [comment]
Just tried updating an existing working app service running 4.0.1 and it now just shows the default Azure app service page as well, the naming tool is gone? Is there a way to revert?

**Comment by epfaffinger** [comment]
Is there a way to push v 4.0.1, I am dead in the water here?

**Comment by BryanSoltis** [comment]
Hi @epfaffinger,

Thank you for your feedback, but sorry to hear you're having issues. We haven't recieved any reports of any trouble deploying, so I am curious as to why yours is not working.

For v4.1.0:
- Have you tried restarting the App Service? (Elementary I know, but sometimes re-deploying an app service doesn't kick in until that happens).
- In your App Service, do you see the files when navigating to the **Advanced Tools** and view the files. In a Linux app plan, you can click the **Browse Directory / Site wwwroot** link on the **Advanced Tools** home page. 

![image](https://github.com/mspnp/AzureNamingTool/assets/13591910/f5b6ff04-e604-4ce0-81c7-a74cd4001af5)

- In the Advanced Tools, you may be able to view some more logs to see if there is anything going on.


For v4.0.1:
- You can download the [v4.0.1 release zip file](https://github.com/mspnp/AzureNamingTool/releases/tag/v4.0.1). Once downloaded, y9ou can open that in Visual Studio and do a **Publish** to your App Service. This will overwrite the site on your service with the previous version.

https://learn.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components-resources?view=vs-2022#azure

Hope this helps. Let me know if you find anything in your logs/findings and I'll if I can figure out why yours is failing. 

- Bryan

**Comment by epfaffinger** [comment]
Hi @Bryan ***@***.***>,

Thanks so much for the quick reply. I am not a developer but an Azure Admin so I am fairly new with Git/GitHub so I really appreciate your help (and patience 😊 ).


  1.  I have tried restarting the app service and have deployed fresh multiple times with the same results.
  2.  Below is a screen shot of the files:

[A screenshot of a computer  Description automatically generated]

[A screenshot of a computer  Description automatically generated]
[A screenshot of a computer  Description automatically generated]
[A screenshot of a computer  Description automatically generated]
[A screenshot of a computer  Description automatically generated]
[A screenshot of a computer  Description automatically generated]

When I try to view the log stream it just sits forever at “Connecting” so can’t see any more info there. If there are any specific logs that would be helpful please let me know and I will gather them.

From an Azure perspective the deployment logs just show success, from GitHub I do have 15 warnings which I assumed were ok?

Annotations
15 warnings
check-secrets<https://github.com/epfaffinger/AzureNamingTool/actions/runs/8298362409/job/22711563000>
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: ***@***.*** For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Show more
build<https://github.com/epfaffinger/AzureNamingTool/actions/runs/8298362409/job/22711571597>
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: ***@***.***, ***@***.***, ***@***.***, ***@***.*** For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Show more
build: src/Helpers/ConfigurationHelper.cs#L988<https://github.com/epfaffinger/AzureNamingTool/commit/9350bec2fabc48a3a1d92abe72fed937272e5ecb#annotation_19331958215>
Converting null literal or possible null value to non-nullable type.
build: tests/AzureNamingTool.UiTests/HostAddressDetails.cs#L5<https://github.com/epfaffinger/AzureNamingTool/commit/9350bec2fabc48a3a1d92abe72fed937272e5ecb#annotation_19331958226>
Non-nullable property 'Address' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
build: tests/AzureNamingTool.UiTests/Contexts/ContextBase.cs#L33<https://github.com/epfaffinger/AzureNamingTool/commit/9350bec2fabc48a3a1d92abe72fed937272e5ecb#annotation_19331958240>
Dereference of a possibly null reference.
build: tests/AzureNamingTool.UiTests/Contexts/ContextBase.cs#L38<https://github.com/epfaffinger/AzureNamingTool/commit/9350bec2fabc48a3a1d92abe72fed937272e5ecb#annotation_19331958247>
Dereference of a possibly null reference.
build: tests/AzureNamingTool.UiTests/Contexts/ContextBase.cs#L43<https://github.com/epfaffinger/AzureNamingTool/commit/9350bec2fabc48a3a1d92abe72fed937272e5ecb#annotation_19331958256>
Dereference of a possibly null reference.
build: src/Helpers/ConfigurationHelper.cs#L988<https://github.com/epfaffinger/AzureNamingTool/commit/9350bec2fabc48a3a1d92abe72fed937272e5ecb#annotation_19331958266>
Converting null literal or possible null value to non-nullable type.
build: tests/AzureNamingTool.UiTests/HostAddressDetails.cs#L5<https://github.com/epfaffinger/AzureNamingTool/commit/9350bec2fabc48a3a1d92abe72fed937272e5ecb#annotation_19331958281>
Non-nullable property 'Address' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
build: tests/AzureNamingTool.UiTests/Contexts/ContextBase.cs#L33<https://github.com/epfaffinger/AzureNamingTool/commit/9350bec2fabc48a3a1d92abe72fed937272e5ecb#annotation_19331958298>
Dereference of a possibly null reference.
build: tests/AzureNamingTool.UiTests/Contexts/ContextBase.cs#L38<https://github.com/epfaffinger/AzureNamingTool/commit/9350bec2fabc48a3a1d92abe72fed937272e5ecb#annotation_19331958312>
Dereference of a possibly null reference.
build: tests/AzureNamingTool.UiTests/Contexts/ContextBase.cs#L43<https://github.com/epfaffinger/AzureNamingTool/commit/9350bec2fabc48a3a1d92abe72fed937272e5ecb#annotation_19331958327>
Dereference of a possibly null reference.
build<https://github.com/epfaffinger/AzureNamingTool/actions/runs/8298362409/job/22711571597#step:6:36>
The "--output" option isn't supported when building a solution. Specifying a solution-level output path results in all projects copying outputs to the same directory, which can lead to inconsistent builds.
deploy<https://github.com/epfaffinger/AzureNamingTool/actions/runs/8298362409/job/22711653333>
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: ***@***.***, ***@***.*** For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Show more
deploy<https://github.com/epfaffinger/AzureNamingTool/actions/runs/8298362409/job/22711653333#step:4:2>
Skip setting environment url as environment 'Development' may contain secret.



In the meantime, I will try to publish v4.0.1 via the zip file from Visual Studio Code.

Thanks,
Eric

**Comment by epfaffinger** [comment]
Hi @Bryan ***@***.***>,

Not sure if this helps but I redeployed to an Azure App Service where the app service plan was set to Windows rather than Linux and the naming tool app loads and functions correctly. However, deploying to an app service with a Linux based app service plan does not?

**Comment by epfaffinger** [comment]
Sorry I meant to say that the deploy works on a Windows based App Service but not Linux in my case.

From: Eric Pfaffinger ***@***.***>
Sent: Friday, March 15, 2024 3:58 PM
To: mspnp/AzureNamingTool ***@***.***>; mspnp/AzureNamingTool ***@***.***>; Bryan Soltis ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [mspnp/AzureNamingTool] Deployed 4.1.0 and just getting default Azure App Service page. (Issue #94)

Hi @Bryan ***@***.***>,

Not sure if this helps but I redeployed to an Azure App Service where the app service plan was set to Windows rather than Linux and the naming tool app loads and functions correctly. However, deploying to an app service with a Linux based app service plan does not?

**Comment by epfaffinger** [comment]
I think I found the issue, this may be in your documentation somewhere but I didn't see it if it was but for a Linux based deploy after upgrading you need to go to the app service config general settings and specifiy the startup command as shown below:

[A screenshot of a computer  Description automatically generated]


From: Eric Pfaffinger
Sent: Friday, March 15, 2024 4:09 PM
To: mspnp/AzureNamingTool ***@***.***>; mspnp/AzureNamingTool ***@***.***>; Bryan Soltis ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [mspnp/AzureNamingTool] Deployed 4.1.0 and just getting default Azure App Service page. (Issue #94)

Sorry I meant to say that the deploy works on a Windows based App Service but not Linux in my case.

From: Eric Pfaffinger ***@***.******@***.***>>
Sent: Friday, March 15, 2024 3:58 PM
To: mspnp/AzureNamingTool ***@***.******@***.***>>; mspnp/AzureNamingTool ***@***.******@***.***>>; Bryan Soltis ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [mspnp/AzureNamingTool] Deployed 4.1.0 and just getting default Azure App Service page. (Issue #94)

Hi @Bryan ***@***.***>,

Not sure if this helps but I redeployed to an Azure App Service where the app service plan was set to Windows rather than Linux and the naming tool app loads and functions correctly. However, deploying to an app service with a Linux based app service plan does not?

**Comment by epfaffinger** [comment]
This is resolved, for Linux you need to put the following in the startup command box in the general config of the app service:

dotnet AzureNamingTool.dll

**Comment by BryanSoltis** [comment]
Hi Eric,

A couple of things. First, THANK YOU for all of your feedback and experience with the tool. Hearing from our users is the only way we can improve and ensure the tool is meeting your needs. Second, that's great that you were able to figure out the issue! We did not have that startup command in our documentation, so your feedback helped improve the installation experience. I have added a note to the App Service/GitHub instructions, along with a screenshot.

Thank you again for the great information and please let us know if you encounter any more issues!

- Bryan
