### ISSUE TITLE
Missing Resource Type in Azure Naming Tool for Virtual Desktop

### ISSUE THREAD

**Issue by Crallbit** [mspnp/AzureNamingTool#95]
Tool version
Current version of the Azure Naming Tool you are running. 
V4.0

Is your feature request related to a problem? Please describe.
The Azure naming tool is currently missing the option to specify the resource type for Virtual Desktop resources. When attempting to name resources related to Azure Virtual Desktop, users are unable to select the appropriate resource type, which impacts the consistency and clarity of resource naming conventions.

Describe the solution you'd like
I implemet it manuall in the Json File and import it again.

**Expected Behavior:**
The Azure naming tool should include an option to specify the resource type for Azure Virtual Desktop resources, allowing users to adhere to consistent naming conventions and ensure clarity in resource naming.

**Comment by DDRosenxt** [comment]
@Crallbit Hi,
The json file can be uploaded using the API. Add a new item to the end of the list, specify the next sequence number for the ID, select the rest of the parameters, and upload the whole file again.

**Comment by BryanSoltis** [comment]
Hi @Crallbit ,

v4.3.0 was released with Custom Resource Type support. Please review the release notes and update to the latest version to customize your resource types.

https://github.com/mspnp/AzureNamingTool/wiki/v4.3.0

Bryan
