### ISSUE TITLE
Typo in dotnet command on Wiki page

### ISSUE THREAD

**Issue by filipvagner** [mspnp/AzureNamingTool#96]
**Tool version**
[Current version](https://github.com/mspnp/AzureNamingTool/tree/9350bec2fabc48a3a1d92abe72fed937272e5ecb) of the Azure Naming Tool you are running.

**Describe the bug**
On [Wiki page](https://github.com/mspnp/AzureNamingTool/wiki/Run-as-an-Azure-Web-App-Using-GitHub-Action) for this project in section **5. Enable GitHub Action** in _Notes_ there is typo in command `dontnet AzureNamingTool.dll`  (do**n**tnet) and it should be `dotnet AzureNamingTool.dll`

**To Reproduce**
Nothing to do to reproduce

**Expected behavior**
After fix, web application is loading as expected.

**Installation Method**
[Following](https://github.com/mspnp/AzureNamingTool/wiki/Run-as-an-Azure-Web-App-Using-GitHub-Action) installation method used.

**Additional context**
If you will fix it, I do believe it will save some troubleshooting to people like me, who just copy paste that command and do not read it :) Thank you.

**Comment by BryanSoltis** [comment]
Thank you, @filipvagner!  I've updated the documentation with the correct command.

-Bryan
