### ISSUE TITLE
Fabric Naming Standards

### ISSUE THREAD

**Issue by DuersinKurtdinext** [mspnp/AzureNamingTool#97]
**Tool version**
4.1.0

**Is your feature request related to a problem? Please describe.**
We want to name Services and components within Microsoft Fabric

**Describe the solution you'd like**
aabreviations for:
fabric = fab
Fabric Workspaces = ws (equates to Power BI Workspace)
Fabric Lakehouse = fablh (LH)
Fabric SQL Analytical Endpoint = fabsae
Fabric Synapse Warehouse = fabdwh
Fabric Synapse Data Science = fabdsc
Fabric ML-Modell = fabdscmlmod
Fabric Expermient = fabdscexp
Fabric Notebook = fabnb
Fabric Environments = fabenv
Fabric Spark Job = sparkjob
Fabric Semantic Model = sem
Fabric Data Pipeline = pipe (differ from Azure Data Factory Pipelines)
Fabric Real Time Analytics = rta
Fabric Real Time Analytics KQL-Datenbank = kqldb
Fabric Real Time Analytics KQL-Query = kqlq
Farbric Real Time Analytics Event Stream = evstr
Data Activator Reflexes = darflx
Data Activator Reflex trigger = darflxtr
 
**Describe alternatives you've considered**
defining my own abbreviations

**Additional context**
needed for customer naming conventions

**Comment by BryanSoltis** [comment]
Hi @DuersinKurtdinext ,

v4.3.0 was released with Custom Resource Type support. Please review the release notes and update to the latest version to customize your resource types.

https://github.com/mspnp/AzureNamingTool/wiki/v4.3.0

Bryan

**Comment by DuersinKurtdinext** [comment]
Thanks for adding!
